default:
  image: node:$NODE_VERSION
  tags:
    - linux

stages:
  - test
  - build
  - deploy

variables:
  DEPLOY_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  BUILDCACHE_IMAGE: $CI_REGISTRY_IMAGE:buildcache

build-test:
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  image: docker:$DOCKER_VERSION
  services:
    - docker:$DOCKER_VERSION-dind
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY --username $CI_REGISTRY_USER --password-stdin
    - docker pull $BUILDCACHE_IMAGE || true
    - docker build
      --cache-from $BUILDCACHE_IMAGE
      --build-arg NEXT_PUBLIC_BASE_URL=$NEXT_PUBLIC_BASE_URL
      --build-arg NEXT_PUBLIC_SERVER_BASE_URL=$NEXT_PRIVATE_BASE_URL
      .

sast:
  stage: test

build:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  image: docker:$DOCKER_VERSION
  services:
    - docker:$DOCKER_VERSION-dind
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY --username $CI_REGISTRY_USER --password-stdin
    - docker pull $BUILDCACHE_IMAGE || true
    - docker build
      --build-arg BUILDKIT_INLINE_CACHE=1
      --cache-from $BUILDCACHE_IMAGE
      --build-arg NEXT_PUBLIC_BASE_URL=$NEXT_PUBLIC_BASE_URL
      --build-arg NEXT_PUBLIC_SERVER_BASE_URL=$NEXT_PRIVATE_BASE_URL
      --tag $BUILDCACHE_IMAGE
      --tag $DEPLOY_IMAGE
      .
    - docker push $BUILDCACHE_IMAGE
    - docker push $DEPLOY_IMAGE

deploy:
  stage: deploy
  image:
    name: bitnami/kubectl:$KUBECTL_VERSION
    entrypoint: [ '' ]
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - kubectl config use-context $KUBE_CONTEXT
    - kubectl config set-context --current --namespace $KUBE_NAMESPACE
    - kubectl set image deploy/$CI_PROJECT_NAME nextjs=$DEPLOY_IMAGE
    - kubectl rollout status deploy/$CI_PROJECT_NAME
  environment:
    name: Production
    url: https://new.timobio.com

include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
